# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
   ffc-sfd-file-processor:
    build:
      target: development
    image: ffc-sfd-file-processor-development
    container_name: ffc-sfd-file-processor-development
    ports:
      - "3019:3019"
      - "9019:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      
