# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfd-file-processor:
    build:
      target: development
    image: ffc-sfd-file-processor-development
    container_name: ffc-sfd-file-processor-development
    ports:
      - "3019:3019"
      - "9019:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment:
      STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-sfd-file-processor-azurite:10000/devstoreaccount1;

  ffc-sfd-file-processor-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10019:10000"

  ngrok:
    image: ngrok/ngrok:latest
    command: 
      - "http"
      - "ffc-sfd-file-processor-development:3019"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  azurite_data: 
      
