services: 
  ffc-sfd-file-processor:
    build:
      context: .
      target: production
    image: ffc-sfd-file-processor
    depends_on:
      - ffc-sfd-file-processor-azurite
    container_name: ffc-sfd-file-processor
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-file-processor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AUTH_HOST: ${AUTH_HOST:-http://ffc-sfd-proxy:3000}
      GATEWAY_HOST: ${GATEWAY_HOST:-http://localhost:3000}
      DATA_HOST: ${DATA_HOST:-http://ffc-sfd-data:3004/graphql}
      AHWP_HOST: ${AHWP_HOST:-http://localhost:3010}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
  
  ffc-sfd-file-processor-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.9.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-sfd-file-processor-azurite
