- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: GATEWAY_HOST
  value: "https://ffc-sfd.snd4.adp.defra.gov.uk"
- key: STORAGE_ACCOUNT_ENDPOINT
  value: https://ffcsfdstorage01.blob.core.windows.net/
- key: STORAGE_ACCOUNT_NAME
  value: "ffc-sfd"
- key: STORAGE_CONTAINER
  value: "test"
- key: AHWP_HOST
  value: "https://ffc-sfd-ahwp-stub.snd4.adp.defra.gov.uk"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: FILE_RECEIVER_TOPIC_ADDRESS
  value: "fcp-sfd-file-metadata"
- key: FILE_RECEIVER_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-file-receiver"