- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: GATEWAY_HOST
  value: "https://ffc-sfd.snd4.adp.defra.gov.uk"
- key: STORAGE_ACCOUNT_ENDPOINT
  value: https://ffc-sfd.blob.core.windows.net
- key: STORAGE_ACCOUNT_NAME
  value: "ffc-sfd"
- key: STORAGE_CONTAINER
  value: "ffc-sfd-file-processor"
- key: AHWP_HOST
  value: "https://ffc-sfd-ahwp-stub.snd4.adp.defra.gov.uk"
- key: STORAGE_USE_CONNECTION_STRING
  value: "false"