apiVersion: v2
name: ffc-sfd-file-processor-infra
description: An ASO Helm chart to deploy the ADP Backend POC Infrastructure
version: 0.0.2
dependencies:
  - name: adp-aso-helm-library
    version: ^2.0.0
    repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-aso-helm-library
